const PKEY='vmw_products',CKEY='vmw_cart';let activeCat='All';
const seed=[
{id:'p1',name:'Black Check Hoodie Set',category:'Winter Set',price:1599,badge:'NEW',sizes:['S','M','L','XL','XXL'],details:'Black-grey checked hooded shirt, white inner & black jogger set',image:'images/plaid-hoodie-black-set.jpg'},
{id:'p2',name:'Charcoal Wide Fit Jeans',category:'Jeans',price:899,badge:'TRENDING',sizes:['28','30','32','34','36'],details:'Stylish charcoal wide-fit denim jeans',image:'images/charcoal-wide-jeans.jpg'},
{id:'p3',name:'Navy White Smart Set',category:'Shirts',price:1399,badge:'SMART',sizes:['S','M','L','XL','XXL'],details:'Navy shirt with white trouser and white inner',image:'images/navy-white-smart-set.jpg'},
{id:'p4',name:'Grey Black Formal Set',category:'Shirts',price:1499,badge:'FEATURED',sizes:['S','M','L','XL','XXL'],details:'Light grey shirt with black trouser, clean smart look',image:'images/grey-black-shirt-trouser-set.jpg'},
{id:'p5',name:'Black Graphic Street Set',category:'Sweatshirts',price:999,badge:'HOT',sizes:['S','M','L','XL','XXL'],details:'Black graphic sweatshirt with matching black pant',image:'images/black-graphic-set.jpg'}];
function getP(){let p=JSON.parse(localStorage.getItem(PKEY)||'null');if(!p){localStorage.setItem(PKEY,JSON.stringify(seed));return seed}return p}
function getC(){return JSON.parse(localStorage.getItem(CKEY)||'[]')}function saveC(c){localStorage.setItem(CKEY,JSON.stringify(c));renderCart()}
function cats(){let cs=['All',...new Set(getP().map(p=>p.category))];let el=document.getElementById('categories');if(!el)return;el.innerHTML=cs.map(c=>`<button class="category ${activeCat===c?'active':''}" onclick="setCat(${JSON.stringify(c)})">${c}</button>`).join('')}
function setCat(c){activeCat=c;cats();render()}
function render(){cats();let q=(document.getElementById('search')?.value||'').toLowerCase(),box=document.getElementById('products');if(!box)return;let ps=getP().filter(p=>(activeCat==='All'||p.category===activeCat)&&(p.name+' '+p.category+' '+p.details).toLowerCase().includes(q));box.innerHTML=ps.map(p=>`<article><div class="pic"><img src="${p.image}" alt="${esc(p.name)}" onerror="this.style.display='none'"><span>${p.badge||''}</span></div><div class="info"><small>${esc(p.category)}</small><h3>${esc(p.name)}</h3><p>${esc(p.details||'')}</p><strong>₹${Number(p.price).toLocaleString('en-IN')}</strong><div class="size-row"><b>Size:</b><select id="size-${p.id}">${p.sizes.map(s=>`<option>${esc(s)}</option>`).join('')}</select></div><div class="product-actions"><button onclick="add('${p.id}')">🛒 Add to Cart</button><button class="alt" onclick="wa('${p.id}')">WhatsApp</button></div></div></article>`).join('')||'<p>Is category/search me product nahi mila.</p>'}
function add(id){let p=getP().find(x=>x.id===id),size=document.getElementById('size-'+id)?.value||p.sizes[0],c=getC(),same=c.find(x=>x.id===id&&x.size===size);if(same)same.qty++;else c.push({id,size,qty:1});saveC(c);alert(p.name+' cart me add ho gaya.')} 
function wa(id){let p=getP().find(x=>x.id===id),size=document.getElementById('size-'+id)?.value||p.sizes[0],m=`Hello Vicky Mans Wear,%0AProduct: ${encodeURIComponent(p.name)}%0APrice: ₹${p.price}%0ASize: ${encodeURIComponent(size)}%0AQuantity: 1%0AMujhe availability aur Ghughri 10 KM delivery ki jaankari chahiye.`;open('https://wa.me/918815033967?text='+m,'_blank')}
function openCart(){document.getElementById('cart').classList.add('show');renderCart()}function closeCart(){document.getElementById('cart').classList.remove('show')}
function renderCart(){let c=getC(),ps=getP(),t=0;document.getElementById('count').textContent=c.reduce((a,x)=>a+x.qty,0);document.getElementById('items').innerHTML=c.map((x,i)=>{let p=ps.find(y=>y.id===x.id);if(!p)return '';t+=p.price*x.qty;return `<div class="row"><div><b>${esc(p.name)}</b><br><small>Size ${esc(x.size)} · Qty ${x.qty}</small></div><button onclick="removeItem(${i})">Remove</button></div>`}).join('')||'<p>Cart empty hai.</p>';document.getElementById('total').textContent='₹'+t.toLocaleString('en-IN')}
function removeItem(i){let c=getC();c.splice(i,1);saveC(c)}function checkout(){if(getC().length)location.href='checkout.html';else alert('Pehle product cart me add karein.')}function esc(v){return String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}render();renderCart();
